# Generated by Django 3.0.5 on 2021-09-14 07:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_customuser_zip_code'),
        ('main', '0064_auto_20210914_1346'),
        ('dashboard', '0003_auto_20210907_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2021, 9, 14, 7, 46, 33, 684067, tzinfo=utc))),
                ('products', models.ManyToManyField(blank=True, to='main.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.CustomUser')),
            ],
        ),
    ]
