# Generated by Django 3.0.5 on 2021-09-14 07:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210914_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 14, 7, 49, 38, 371033, tzinfo=utc)),
        ),
    ]
