# Generated by Django 3.0.5 on 2021-09-21 05:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210921_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 5, 1, 14, 118818, tzinfo=utc)),
        ),
    ]
