# Generated by Django 3.0.5 on 2021-09-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20210921_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='last_updated',
            field=models.DateTimeField(),
        ),
    ]
