# Generated by Django 3.0.5 on 2021-09-23 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_product_stock_last_updated'),
        ('authentication', '0028_customuser_zip_code'),
        ('dashboard', '0012_auto_20210921_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(blank=True, to='main.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.CustomUser')),
            ],
        ),
    ]
