# Generated by Django 3.0.5 on 2021-09-24 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_customuser_zip_code'),
        ('main', '0074_product_stock_last_updated'),
        ('dashboard', '0013_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Packaging', 'Packaging'), ('Delivering', 'Delivering'), ('Deliverd', 'Deliverd')], default='Packaging', max_length=255)),
                ('payment_made', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(blank=True, to='main.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.CustomUser')),
            ],
        ),
    ]
