# Generated by Django 3.0.5 on 2021-09-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20210925_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Packaging', 'Packaging'), ('Delivering', 'Delivering'), ('Deliverd', 'Delivered')], default='Packaging', max_length=255),
        ),
    ]
