# Generated by Django 3.2.8 on 2021-11-01 05:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_order_date_of_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_of_order',
        ),
        migrations.AddField(
            model_name='order',
            name='time_of_order',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 5, 46, 50, 457226, tzinfo=utc)),
        ),
    ]
