# Generated by Django 3.2.8 on 2021-11-08 05:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20211101_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_of_order',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 5, 12, 7, 299127, tzinfo=utc)),
        ),
    ]
