# Generated by Django 3.2.8 on 2021-11-09 07:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_alter_order_time_of_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_of_order',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 7, 1, 38, 867121, tzinfo=utc)),
        ),
    ]
