# Generated by Django 3.0.5 on 2020-10-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='photographer',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
