# Generated by Django 3.0.5 on 2020-10-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_brand_photographer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='photographer',
            new_name='image_photographer',
        ),
        migrations.AddField(
            model_name='brand',
            name='image_photographer_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
