# Generated by Django 3.0.5 on 2020-10-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201008_1118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='Category',
        ),
    ]
