# Generated by Django 3.0.5 on 2020-10-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_brand_in_sub_category',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/baby'),
        ),
    ]
