# Generated by Django 3.0.5 on 2020-11-01 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201101_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttype',
            old_name='category',
            new_name='sub_category',
        ),
    ]
