# Generated by Django 3.0.5 on 2020-11-01 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201101_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='sub_category_category',
        ),
        migrations.AddField(
            model_name='producttype',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.SubCategory'),
        ),
    ]
