# Generated by Django 3.0.5 on 2020-11-01 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20201101_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='sub_category',
        ),
    ]
