# Generated by Django 3.0.5 on 2020-11-01 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_producttype_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='year_in_school',
        ),
    ]
