# Generated by Django 3.0.5 on 2020-11-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_producttype_year_in_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='year_in_school',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default='cd', max_length=200),
        ),
    ]
