# Generated by Django 3.0.5 on 2020-11-01 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20201101_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='year_in_school',
        ),
    ]
