# Generated by Django 3.0.5 on 2020-11-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_producttype_sub_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name'], 'verbose_name_plural': 'Product Types'},
        ),
        migrations.AlterField(
            model_name='producttype',
            name='image_photographer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
