# Generated by Django 3.0.5 on 2020-11-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20201104_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
