# Generated by Django 3.0.5 on 2020-11-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20201105_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='sub_category_title',
            field=models.CharField(default='Product Types', max_length=30),
        ),
    ]
