# Generated by Django 3.0.5 on 2020-11-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_producttype_sub_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='sub_category_title',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='sub_category_title',
            field=models.CharField(default='Product Types', max_length=30),
        ),
    ]
