# Generated by Django 3.0.5 on 2020-11-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='filter_category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
