# Generated by Django 3.0.5 on 2020-11-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_filter_filter_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'ordering': ['product_type', 'filter_category', 'name']},
        ),
        migrations.AddField(
            model_name='filter',
            name='background_color',
            field=models.CharField(default='#f5f5f5', max_length=9),
        ),
        migrations.AddField(
            model_name='filter',
            name='foreground_color',
            field=models.CharField(default='#2f2f2f', max_length=9),
        ),
    ]
