# Generated by Django 3.0.5 on 2020-11-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20201129_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='background_color',
            field=models.CharField(default='#fafafa', max_length=9),
        ),
    ]
