# Generated by Django 3.0.5 on 2020-11-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20201129_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='background_color',
        ),
    ]
