# Generated by Django 3.0.5 on 2020-11-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_filter_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='background_color',
            field=models.CharField(default='#fafafa', max_length=9),
        ),
    ]
