# Generated by Django 3.0.5 on 2020-12-09 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20201209_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.URLField(blank=True, null=True)),
                ('image_photographer', models.CharField(blank=True, max_length=255, null=True)),
                ('image_photographer_url', models.URLField(blank=True)),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.SubCategory')),
            ],
            options={
                'verbose_name_plural': 'Product Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('filter_category', models.CharField(blank=True, max_length=30, null=True)),
                ('background_color', models.CharField(default='#fafafa', max_length=9)),
                ('foreground_color', models.CharField(default='#2f2f2f', max_length=9)),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ProductType')),
            ],
            options={
                'ordering': ['product_type', 'filter_category', 'name'],
            },
        ),
    ]
