# Generated by Django 3.0.5 on 2020-12-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_filter_producttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='image_photographer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image_photographer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
