# Generated by Django 3.0.5 on 2020-12-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_producttype_parent_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='parent_product_type',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
    ]
