# Generated by Django 3.0.5 on 2021-08-23 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20201223_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='products')),
                ('condition', models.CharField(max_length=255)),
                ('shipping', models.CharField(max_length=255)),
                ('returns', models.CharField(max_length=255)),
                ('payments', models.CharField(max_length=255)),
                ('product_does_not_ship_to', models.TextField()),
                ('payments_paypal', models.BooleanField(default=False)),
                ('payments_master_card', models.BooleanField(default=False)),
                ('payments_visa', models.BooleanField(default=False)),
                ('payments_cod', models.BooleanField(default=False)),
                ('features', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
            ],
        ),
    ]
