# Generated by Django 3.0.5 on 2021-08-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20210823_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='filters',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ManyToManyField(to='main.SubCategory'),
        ),
    ]
