# Generated by Django 3.0.5 on 2021-08-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20210824_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
