# Generated by Django 3.0.5 on 2021-08-24 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_customuser_huid'),
        ('main', '0056_product_shipping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.CustomUser'),
            preserve_default=False,
        ),
    ]
