# Generated by Django 3.0.5 on 2021-08-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20210825_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='payments',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='payments_cod',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='payments_master_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='payments_paypal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='payments_visa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_does_not_ship_to',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='returns',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_price',
            field=models.FloatField(),
        ),
    ]
