# Generated by Django 3.0.5 on 2021-08-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_location',
            field=models.TextField(default='New York, USA'),
            preserve_default=False,
        ),
    ]
