# Generated by Django 3.0.5 on 2021-09-14 07:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_auto_20210914_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 14, 7, 48, 53, 298070, tzinfo=utc)),
        ),
    ]
