# Generated by Django 3.0.5 on 2021-09-14 07:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_auto_20210914_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 14, 7, 52, 18, 139032, tzinfo=utc)),
        ),
    ]
