# Generated by Django 3.0.5 on 2021-09-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_auto_20210921_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
