# Generated by Django 3.0.5 on 2021-09-25 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_customuser_zip_code'),
        ('main', '0074_product_stock_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.CustomUser'),
        ),
    ]
