# Generated by Django 3.2.8 on 2021-10-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filters',
            field=models.ManyToManyField(null=True, to='main.Filter'),
        ),
    ]
