# Generated by Django 3.2.8 on 2021-10-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_product_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=models.ManyToManyField(editable=False, null=True, to='main.Filter'),
        ),
    ]
