# Generated by Django 3.2.8 on 2021-10-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_alter_product_filters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='payments',
        ),
    ]
