# Generated by Django 3.2.8 on 2021-11-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_remove_product_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
