# Generated by Django 3.2.8 on 2021-11-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='json',
            field=models.JSONField(default={'email': 'someting'}),
        ),
    ]
