# Generated by Django 3.2.8 on 2021-11-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_product_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='json',
        ),
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.JSONField(default=''),
        ),
    ]
