# Generated by Django 3.2.8 on 2021-11-09 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_auto_20211109_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='views',
        ),
    ]
