# Generated by Django 3.2.8 on 2021-11-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_product_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='views',
        ),
    ]
