# Generated by Django 3.0.5 on 2021-07-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerifiedUser',
        ),
    ]
