# Generated by Django 3.0.5 on 2021-07-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210721_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifieduser',
            name='huid',
            field=models.TextField(default='', max_length=32),
        ),
    ]
