# Generated by Django 3.0.5 on 2021-07-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_verifieduser_huid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifieduser',
            name='huid',
            field=models.CharField(default='', max_length=32),
        ),
    ]
