# Generated by Django 3.0.5 on 2021-08-23 04:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0006_auto_20210721_1929'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerifiedUser',
            new_name='CustomUser',
        ),
    ]
