# Generated by Django 3.0.5 on 2021-08-23 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20210823_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='huid',
        ),
    ]
