# Generated by Django 3.0.5 on 2021-08-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_customuser_huid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='huid',
            field=models.CharField(default='', max_length=32),
        ),
    ]
