# Generated by Django 3.0.5 on 2021-08-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_customuser_huid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('NS', 'new_seller'), ('TRS', 'top_rated_seller'), ('VS', 'verified_seller')], default='NS', max_length=3),
        ),
    ]
