# Generated by Django 3.0.5 on 2021-08-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_customuser_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('NS', 'New Seller'), ('TRS', 'Top Rated Seller'), ('VS', 'Verified Seller')], default='NS', max_length=3),
        ),
    ]
