# Generated by Django 3.0.5 on 2021-08-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20210824_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('New Seller', 'New Seller'), ('Top Rated Seller', 'Top Rated Seller'), ('Verified Seller', 'Verified Seller')], default='New Seller', max_length=255),
        ),
    ]
