# Generated by Django 3.0.5 on 2021-08-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20210824_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='communication',
            field=models.FloatField(default=56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='returns',
            field=models.FloatField(default=99),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='shipping',
            field=models.FloatField(default=45),
            preserve_default=False,
        ),
    ]
