# Generated by Django 3.0.5 on 2021-08-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20210824_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='', upload_to='profile_images'),
            preserve_default=False,
        ),
    ]
