# Generated by Django 3.0.5 on 2021-08-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20210825_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='/static/base/img/profile_images/user.png', upload_to='profile_images'),
        ),
    ]
