# Generated by Django 3.0.5 on 2021-08-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_auto_20210825_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='profile_images/user.png', upload_to='profile_images'),
        ),
    ]
