# Generated by Django 3.0.5 on 2021-08-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_auto_20210826_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='communication',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='returns',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='shipping',
            field=models.FloatField(null=True),
        ),
    ]
