# Generated by Django 3.0.5 on 2021-08-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_auto_20210826_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cover_image',
            field=models.ImageField(default='cover_images/cover.png', upload_to='cover_images'),
        ),
    ]
