# Generated by Django 3.0.5 on 2021-08-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_auto_20210829_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cover_image',
        ),
    ]
