# Generated by Django 3.0.5 on 2021-09-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_auto_20210905_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
