# Generated by Django 3.0.5 on 2021-09-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state_province',
            field=models.CharField(default='', max_length=32),
        ),
    ]
