# Generated by Django 3.0.5 on 2021-09-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_auto_20210905_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='zip_code',
            field=models.CharField(default='', max_length=32),
        ),
    ]
